### ISSUE TITLE
Issues with the for loop and the unset statement

### ISSUE THREAD

**Issue by inspektorsowa** [fezfez/php-to-zephir#13]
Hi there,
it seems that the library doesn't manage with the "for" loop and the "unset" statement.

This is my PHP code:

```php
<?php
namespace Brainusers;
class ZephirTest {
	static public function hello() {
		$obj = array();
		for ($i=0; $i<1000; $i++) {
			$obj[] = new ZephirTest();
		}
		unset($obj);
	}
}
```

Output is:
```zephir
namespace Brainusers;

class ZephirTest
{
    public static function hello() -> void
    {
        var obj, i;


        let obj =  [];
        for let i = 0; i < 1000; let i++ {
            let obj[] = new ZephirTest();
        }
        unset(obj);

    }

}
```

Trying to build:
```bash
$ zephir build
Zephir\ParseException: Syntax error in /php2zephir/brainusers/brainusers/zephirtest.zep on line 11

	        for let i = 0; i < 1000; let i++ {
	--------------^
```

After changed to for i in range(0,1000) there is a problem with unset:

```bash
$ zephir build
Zephir\CompilerException: Cannot use expression type: variable in "unset" in /php2zephir/brainusers/brainusers/zephirtest.zep on line 14

	        unset(obj);
	-----------------^
```

**Comment by fezfez** [comment]
Hi !

I fix the for loop. 

For the unset statement, the translation is correct maybe open a ticket at https://github.com/phalcon/zephir/issues/

Thanks for the report !

**Comment by inspektorsowa** [comment]
Thank you for a such quick reply.

The unset() in PHP is more like a language expression than a function.
```php
unset($a);
```
However in Zephir to unset a variable you have to use it without brackets (like an echo):
```zephir
unset $a;
```

So maybe you can change the converting `unset($a)` in PHP to `unset $a` in Zephir?

**Comment by fezfez** [comment]
I cant test Zephir compilation right now, so i trust you and i change the unset translation.
Can you test with master ?

Thanks !

**Comment by inspektorsowa** [comment]
Now the unset works only for the array elements, but not for variables. I will notify the Zephir devs. Thanks.

**Comment by fezfez** [comment]
Thanks !
