### ISSUE TITLE
Include not supported?

### ISSUE THREAD

**Issue by w3yyb** [fezfez/php-to-zephir#21]
Include not supported?

**Comment by fezfez** [comment]
In my knowledge, Zephir does not suppot include, so its ignore in transformation.

**Comment by zeeshank22** [comment]
Not sure about include, but "require" is supported in "zephir".
I have created an auto-loader with the same.

**Comment by w3yyb** [comment]
if a php file  contain "include" then report error. can't convert to  zephir

**Comment by fezfez** [comment]
Now supported with  920ed948b697f08954642a0db282bdd3cf9f9544

Close.
