### ISSUE TITLE
Abandoned project?

### ISSUE THREAD

**Issue by phackwer** [fezfez/php-to-zephir#34]
Hi, is this project abandoned?

I'm writing a framework and wanted to use this to convert core components to Zephir. But the code here is not compatible with PHP 5.4.16 (RHEL/CentOS default). If it's abandoned, can I fork and make it compatible?

Yeah, I know, 5.4 is old crap, but unfortunatelly, in Brazil, stupidit.. I meant, some idio... errr... Sysadmins only use RHEL official crap.

May I fork it for the Phalcony Rest Framework? I must convert some PHP to Zephir.

**Comment by fezfez** [comment]
This project is not abandoned and you can convert the code with a php 5.5, get the zep file and compile in php 5.4.
If you try to get the project work on php 5.4, you will get realy bad time !
